export const SERVE_STATIC_MODULE_OPTIONS = 'SERVE_STATIC_MODULE_OPTIONS';

export const DEFAULT_ROOT_PATH = 'client';
export const DEFAULT_EXPRESS_RENDER_PATH = '{*any}';
export const DEFAULT_FASTIFY_RENDER_PATH = '*';
